'use client';

import { TRouteDTO, ROUTES } from '@/settings/routes';

const BREAD_CRUMBS: Record<string, TRouteDTO[]> = {};
BREAD_CRUMBS[ROUTES.HOME.path] = [];
BREAD_CRUMBS[ROUTES.DASHBOARD.path] = [ROUTES.DASHBOARD];
BREAD_CRUMBS[ROUTES.FILES.path] = [ROUTES.FILES];
BREAD_CRUMBS[ROUTES.DEBUG.path] = [ROUTES.DEBUG];
BREAD_CRUMBS[ROUTES.ILLUSTRATIONS.path] = [ROUTES.ILLUSTRATIONS];

export { BREAD_CRUMBS };
