'use client';

import { TRouteDTO, ROUTES } from '@/settings/routes';

const BREAD_CRUMBS: Record<string, TRouteDTO[]> = {};
BREAD_CRUMBS[ROUTES.HOME.path] = [];
BREAD_CRUMBS[ROUTES.DASHBOARD.path] = [ROUTES.DASHBOARD];
BREAD_CRUMBS[ROUTES.PROFILE.path] = [ROUTES.PROFILE];
BREAD_CRUMBS[ROUTES.DEBUG.path] = [ROUTES.DEBUG];
BREAD_CRUMBS[ROUTES.ILLUSTRATIONS.path] = [ROUTES.ILLUSTRATIONS];
BREAD_CRUMBS[ROUTES.PARTNERS.path] = [ROUTES.PARTNERS];
BREAD_CRUMBS[ROUTES.USERS.path] = [ROUTES.USERS];

export { BREAD_CRUMBS };
