'use client';

import { TRouteDTO, ROUTES } from '@/settings/routes';

const BREAD_CRUMBS: Record<string, TRouteDTO[]> = {};
BREAD_CRUMBS[ROUTES.HOME.path] = [];
BREAD_CRUMBS[ROUTES.DASHBOARD.path] = [ROUTES.DASHBOARD];
BREAD_CRUMBS[ROUTES.PROFILE.path] = [ROUTES.PROFILE];
// debug
BREAD_CRUMBS[ROUTES.DEBUG.path] = [ROUTES.DEBUG];
BREAD_CRUMBS[ROUTES.DEBUG_LIST_STATIC.path] = [ROUTES.DEBUG_LIST_STATIC];
BREAD_CRUMBS[ROUTES.DEBUG_LIST_LOAD.path] = [ROUTES.DEBUG_LIST_LOAD];

export { BREAD_CRUMBS };
